name = "PowerDynamics"
uuid = "cc46b21f-1b17-51c2-b642-af74c3d3a8be"
authors = ["Hans Würfel", "Tim Kittel", "Jan Liße", "Sabine Auer", "Anton Plietzsch"]
version = "4.0.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitStandardLibrary = "16a59e39-deab-5bd0-87e4-056b12336739"
NetworkDynamics = "22e9dc34-2a0d-11e9-0de0-8588d035468b"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
ArgCheck = "2.3.0"
DataFrames = "1.7.0"
DiffEqCallbacks = "4"
ForwardDiff = "0.10.36, 1"
Graphs = "1.9.0"
LinearAlgebra = "1.10.0"
MacroTools = "0.5.16"
ModelingToolkit = "10"
ModelingToolkitStandardLibrary = "2.11.0"
NetworkDynamics = "0.10.4"
NonlinearSolve = "4"
OrderedCollections = "1.6.3"
Reexport = "1.2.2"
SciMLBase = "2.48.1"
Setfield = "1.1.1"
StaticArrays = "1.9.7"
SymbolicIndexingInterface = "0.3.28"
Symbolics = "6.5.0"
julia = "1.10"
