name = "PowerDynBase"
uuid = "7ffb48b1-f436-5a59-a310-b4407da33972"
authors = ["Tim Kittel <tim.kittel@elena-international.com>"]
version = "0.5.4"

[deps]
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Julia = "=1.0"
SymPy = ">=0.8"

[extras]
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SymPy"]
