name = "MarinePowerDynamics"
uuid = "6a160989-bfe5-4b1a-b51b-7a8c491e4d37"
authors = ["Tim Kittel", "Jan Liße", "Sabine Auer", "Anton Plietzsch", "Hans Würfel", "Alexander Barajas-Ritchie"]
version = "1.0.0"

[deps]
BlockSystems = "4663d367-db1f-4bef-81e7-dc1bd7f7b428"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NetworkDynamics = "22e9dc34-2a0d-11e9-0de0-8588d035468b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PowerModelsACDC = "ff45984e-d068-5f4c-9e32-c4133509d236"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLNLSolve = "e9a6253c-8580-4d32-9898-8661bb511710"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
BlockSystems = "0.4.2"
CSV = "0.10.15"
ControlSystems = "1"
DiffEqBase = "^6.9.4"
DiffEqCallbacks = "^2"
Graphs = "1.4"
Interpolations = "0.16.1"
Ipopt = "0.7, 0.8, 0.9, 1"
JSON = "^0.21.0"
Lazy = "^0.14.0, 0.15"
MacroTools = "^0.5.1"
ModelingToolkit = "8"
NLsolve = "^4.1.0"
NetworkDynamics = "0.8"
OrderedCollections = "1.3"
OrdinaryDiffEq = "^5.17.2, 6"
Parameters = "^0.12.0"
PowerModels = "0.18, 0.19, 0.20"
PowerModelsACDC = "^0.4, 0.5, 0.6, 0.7"
RecipesBase = "0.7.0,0.8.0, 1.0"
SciMLBase = "1, 2.0 - 2.10"
SciMLNLSolve = "0.1"
Setfield = "1"
StaticArrays = "1"
SteadyStateDiffEq = "1, 2"
TimerOutputs = "0.5.24"
Unitful = "1"
julia = "1.6"

[extras]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Crayons", "JLD2"]
