name = "PowerDynamicsTesting"
uuid = "97638210-66c4-447f-990e-d00c2b05d7ca"
authors = ["Hans Würfel <git@wuerfel.io>"]
version = "0.1.0"

[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NetworkDynamics = "22e9dc34-2a0d-11e9-0de0-8588d035468b"
PowerDynamics = "cc46b21f-1b17-51c2-b642-af74c3d3a8be"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEqNonlinearSolve = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
NetworkDynamics = {rev = "main", url = "https://github.com/JuliaDynamics/NetworkDynamics.jl"}
PowerDynamics = {path = ".."}

[compat]
DiffEqCallbacks = "≥0.0.1"
Graphs = "≥0.0.1"
JLD2 = "0.5.2"
Makie = "0.24"
ModelingToolkit = "≥0.0.1"
NetworkDynamics = "≥0.0.1"
PowerDynamics = "≥0.0.1"
OrderedCollections = "≥0.0.1"
OrdinaryDiffEqNonlinearSolve = "1.2.1"
OrdinaryDiffEqRosenbrock = "1.2.0"
SciMLBase = "≥0.0.1"
Test = "1.10.0"
julia = "1.10"
