name = "PowerDynamics-Docs"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitStandardLibrary = "16a59e39-deab-5bd0-87e4-056b12336739"
NetworkDynamics = "22e9dc34-2a0d-11e9-0de0-8588d035468b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEqNonlinearSolve = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
PowerDynamics = "cc46b21f-1b17-51c2-b642-af74c3d3a8be"
PowerDynamicsTesting = "97638210-66c4-447f-990e-d00c2b05d7ca"
SparseConnectivityTracer = "9f842d2f-2579-4b1d-911e-f412cf18a3f5"

[sources]
PowerDynamics = {path = ".."}
PowerDynamicsTesting = {path = "../PowerDynamicsTesting"}

[compat]
CSV = "0.10.15"
CairoMakie = "0.15"
DataFrames = "≥0.0.1"
DiffEqCallbacks = "≥0.0.1"
Documenter = "1.11.4"
DocumenterInterLinks = "1.0.0"
Graphs = "≥0.0.1"
JSON = "0.21.4"
Literate = "2.20.1"
ModelingToolkit = "≥0.0.1"
NetworkDynamics = "≥0.0.1"
OrderedCollections = "≥0.0.1"
OrdinaryDiffEqNonlinearSolve = "1.9.0"
OrdinaryDiffEqRosenbrock = "1.10.0"
OrdinaryDiffEqTsit5 = "1.1.0"
PowerDynamics = "≥0.0.1"
PowerDynamicsTesting = "≥0.0.1"
